

//TODO: Have different objects/functions for sounds,spritesheets,images.
//TODO: Preload all images into textures
//TODO: Handle spritesheet into textures
//TODO: Preload all sounds

export enum GameImage {
  BUTTON,
  BUTTON_HOVERED,
  ICON_BUTTON,
  ICON_BUTTON_HOVERED,
  SPRITESHEET,
  RIVER,
  POPUP_BOX,
  DEBUG
}

// Each key matches the filename (minus .png) of a file somewhere under
// client/assets/sprites/ - which subfolder it lives in doesn't matter, only the
// name. SpriteAtlas looks a region up by its key (SpriteRegion[region]). Starts at 1
// so a region is always truthy. Adding a sprite means adding a file named after its
// key and running `npm run generate-sprites`.
export enum SpriteRegion {
  //Units
  UNIT_WARRIOR = 1,
  UNIT_SCOUT,
  UNIT_ARCHER,
  UNIT_BUILDER,
  UNIT_CAMEL_ARCHER,
  UNIT_CARAVAN,
  UNIT_CATAPULT,
  UNIT_COMPOSITE_BOWMAN,
  UNIT_CROSSBOWMAN,
  UNIT_HORSEMAN,
  UNIT_ROMAN_LEGION,
  UNIT_SETTLER,
  UNIT_CARGO_SHIP,
  UNIT_WORK_BOAT,
  UNIT_GALLEY,
  UNIT_SPEARMAN,
  UNIT_CHARIOT_ARCHER,
  UNIT_SWORDSMAN,
  UNIT_LEGION,
  UNIT_PIKEMAN,
  //Tiles
  TILE_BLANK,
  TILE_SHALLOW_OCEAN,
  TILE_OCEAN,
  TILE_FRESHWATER,
  TILE_GRASS,
  TILE_GRASS_HILL,
  TILE_MOUNTAIN,
  TILE_DESERT,
  TILE_DESERT_HILL,
  TILE_PLAINS,
  TILE_PLAINS_HILL,
  TILE_TUNDRA,
  TILE_TUNDRA_HILL,
  TILE_SNOW,
  TILE_SNOW_HILL,
  TILE_JUNGLE,
  TILE_FOREST,
  TILE_FLOODPLAINS,
  TILE_CATTLE,
  TILE_SHEEP,
  TILE_FISH,
  TILE_CRAB,
  TILE_WHALES,
  TILE_TURTLES,
  TILE_HORSES,
  TILE_COPPER,
  TILE_GOLD,
  TILE_IRON,
  TILE_COTTON,
  TILE_CITRUS,
  TILE_OLIVES,
  TILE_STONE,
  TILE_CITY,
  TILE_BARBARIAN_CAMP,
  TILE_HOVERED,
  TILE_IMPROVED_HORSES,
  TILE_IMPROVED_CATTLE,
  TILE_IMPROVED_SHEEP,
  TILE_COPPER_MINE,
  TILE_IRON_MINE,
  TILE_STONE_QUARRY,
  TILE_IMPROVED_FISH,
  TILE_IMPROVED_CRAB,
  TILE_IMPROVED_WHALES,
  TILE_IMPROVED_TURTLES,
  TILE_CITRUS_PLANTATION,
  TILE_COTTON_PLANTATION,
  TILE_OLIVE_PLANTATION,
  TILE_GOLD_MINE,
  TILE_FARM,
  TILE_MINE,
  TILE_LUMBER_MILL,
  TILE_TRADING_POST,
  //Roads - named as on old_java. Each joins the tile's center to two of its sides; see Road.ts.
  ROAD_HORIZONTAL,
  ROAD_HORIZONTAL_BOTTOMLEFT,
  ROAD_HORIZONTAL_BOTTOMRIGHT,
  ROAD_HORIZONTAL_CORNERBOTTOMLEFT,
  ROAD_HORIZONTAL_CORNERBOTTOMRIGHT,
  ROAD_HORIZONTAL_CORNERTOPLEFT,
  ROAD_HORIZONTAL_CORNERTOPRIGHT,
  ROAD_HORIZONTAL_TOPLEFT,
  ROAD_HORIZONTAL_TOPRIGHT,
  ROAD_VERTICAL_CORNERBOTTOM,
  ROAD_VERTICAL_CORNERLEFT,
  ROAD_VERTICAL_CORNERRIGHT,
  ROAD_VERTICAL_CORNERTOP,
  ROAD_VERTICAL_LEFT,
  ROAD_VERTICAL_RIGHT,
  //Icons
  ICON_STAR,
  ICON_UNKNOWN,
  ICON_ROME,
  ICON_MONGOLIA,
  ICON_MAMLUKS,
  ICON_AMERICA,
  ICON_GERMANY,
  ICON_ENGLAND,
  ICON_CUBA,
  ICON_BARBARIAN,
  ICON_CANADA,
  ICON_PRODUCTION,
  ICON_FOOD,
  ICON_MORALE,
  ICON_POPULATION,
  ICON_SCIENCE,
  ICON_CULTURE,
  ICON_GOLD,
  ICON_FAITH,
  ICON_TRADE,
  ICON_DEFENSE,
  ICON_COMBAT,
  ICON_FORTIFY_HEAL,
  ICON_SETTLE,
  ICON_UP_ARROW,
  ICON_DOWN_ARROW,
  ICON_CANCEL,
  ICON_ACCEPT,
  ICON_EMPTY_PASTURE,
  ICON_FARM,
  ICON_MINE,
  ICON_CHOP,
  ICON_HAMMER,
  ICON_GEAR,
  ICON_MOVE,
  ICON_QUESTION,
  ICON_GOTO_LEFT,
  //Buildings
  BUILDING_PALACE,
  BUILDING_MONUMENT,
  BUILDING_AMPHITHEATER,
  BUILDING_AQUEDUCT,
  BUILDING_BAZAAR,
  BUILDING_CHAPEL,
  BUILDING_CIRCUS,
  BUILDING_COLOSSEUM,
  BUILDING_COLOSSUS,
  BUILDING_FORGE,
  BUILDING_GARDEN,
  BUILDING_GRANARY,
  BUILDING_GREAT_LIBRARY,
  BUILDING_GREAT_PYRAMIDS,
  BUILDING_HANGING_GARDENS,
  BUILDING_LIBRARY,
  BUILDING_LIGHTHOUSE,
  BUILDING_MACHU_PICCHU,
  BUILDING_MARKET,
  BUILDING_MINT,
  BUILDING_NATIONAL_COLLEGE,
  BUILDING_SHRINE,
  BUILDING_STATUE_OF_ARES,
  BUILDING_STONEHENGE,
  BUILDING_STONEWORKS,
  BUILDING_TERRACOTTA_ARMY,
  BUILDING_WALL,
  BUILDING_WATERMILL,
  BUILDING_WORKSHOP,
  //Misc
  UNIT_SELECTION_TILE,
  DEBUG1,
  DEBUG2,
  DEBUG3,
  UI_STATUSBAR,
  RADIO_BUTTON_UNSELECTED,
  RADIO_BUTTON_SELECTED,
  UNIT_SELECTION_CIRCLE,
}

// SpriteRegion is keyed by fixed member names, but several call sites look one up
// by a dynamic string (e.g. a unit/tile/icon name from server data). This centralizes
// that one inherently-dynamic lookup instead of scattering implicit-any casts.
export function resolveSpriteRegion(key: string): SpriteRegion {
  return (SpriteRegion as unknown as Record<string, SpriteRegion>)[key];
}


// assets.ts
export const assetList = [
  new URL("../assets/images/ui_button.svg", import.meta.url).href,
  new URL("../assets/images/ui_button_hovered.svg", import.meta.url).href,
  new URL("../assets/images/ui_button.svg", import.meta.url).href,
  new URL("../assets/images/ui_button_hovered.svg", import.meta.url).href,
  new URL("../assets/images/spritesheet.png", import.meta.url).href,
  new URL("../assets/images/river.png", import.meta.url).href,
  new URL("../assets/images/ui_popup_box.svg", import.meta.url).href,
  new URL("../assets/images/debug.png", import.meta.url).href,
  new URL("../assets/images/font.png", import.meta.url).href,
  new URL("../assets/images/logo.png", import.meta.url).href
];