import * as fs from "fs";
import * as path from "path";

// Regenerates client/src/generated/SpriteManifest.ts from every PNG under
// client/assets/sprites/ (searched recursively - subfolders are just for the
// developer's own organization and don't affect lookup). Each file's name
// (minus .png) must match a SpriteRegion value in client/src/Assets.ts exactly.
// Run `npm run generate-sprites` after adding, removing, or renaming a sprite
// file, and commit the result - Vite needs the static `new URL(...)` calls in
// that file to bundle each sprite, so the manifest can't be built dynamically
// at runtime.

const ROOT = path.resolve(__dirname, "..");
const SPRITES_DIR = path.join(ROOT, "client", "assets", "sprites");
const OUTPUT_PATH = path.join(ROOT, "client", "src", "generated", "SpriteManifest.ts");

interface ManifestEntry {
    name: string; // filename minus .png - matches a SpriteRegion value
    relativeUrl: string; // path passed to `new URL(..., import.meta.url)`
}

function walk(dir: string): string[] {
    const files: string[] = [];
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            files.push(...walk(fullPath));
        } else if (entry.name.toLowerCase().endsWith(".png")) {
            files.push(fullPath);
        }
    }
    return files;
}

function collectEntries(): ManifestEntry[] {
    const entries: ManifestEntry[] = [];
    const seen = new Map<string, string>(); // name -> first file path it came from

    for (const filePath of walk(SPRITES_DIR)) {
        const name = path.basename(filePath, ".png");

        if (seen.has(name)) {
            throw new Error(
                `Duplicate sprite name "${name}": ${seen.get(name)} and ${filePath}. ` +
                `Sprite names must be unique across all of client/assets/sprites, regardless of folder.`
            );
        }
        seen.set(name, filePath);

        const relativeUrl = "../../assets/sprites/" + path.relative(SPRITES_DIR, filePath).split(path.sep).join("/");
        entries.push({ name, relativeUrl });
    }

    entries.sort((a, b) => a.name.localeCompare(b.name));
    return entries;
}

function render(entries: ManifestEntry[]): string {
    const lines = entries.map(
        (e) => `  { name: "${e.name}", url: new URL("${e.relativeUrl}", import.meta.url).href },`
    );

    return `// AUTO-GENERATED by scripts/generate_sprite_manifest.ts - do not edit by hand.
// Run \`npm run generate-sprites\` after adding, removing, or renaming a file
// under client/assets/sprites, then commit the change.

export interface SpriteManifestEntry {
  name: string;
  url: string;
}

export const SPRITE_MANIFEST: SpriteManifestEntry[] = [
${lines.join("\n")}
];
`;
}

const entries = collectEntries();
fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, render(entries));
console.log(`Wrote ${entries.length} sprite entries to ${path.relative(ROOT, OUTPUT_PATH)}`);
